<<<<<<< HEAD
baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
=======
baseURL = "https://your-site-name.netlify.app/"
languageCode = "en-us"
title = "My Portfolio"
theme = "PaperMod"

[params]
  author = "Mastermind Mitch"

>>>>>>> 7d03eb4 (Add theme and test contetn)
