baseURL = "https://your-site-name.netlify.app/"
languageCode = "en-us"
title = "My Portfolio"
theme = "PaperMod"

[params]
  author = "Mastermind Mitch"

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 2
